_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 5
                - 53
                - 55
                - 95
                - 105
            "2":
                - 5
                - 53
                - 55
                - 95
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.9.5
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
